name: Checks

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
      with:
        globs: |
          **/*.md

  sanity:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: run sanitycheck.py
      run: python3 ./tools/sanitycheck.py
